const newMovies = [
    {
        title: "Challengers",
        imdbrating: "7.2/10",
        rottenrating: "88%",
        stars: "Mike Faist, Josh O'Connor, Zendaya",
        directors: "Luca Guadagnino",
        plot: "Tashi, a former tennis prodigy turned coach, transformed her husband into a champion. But to overcome a recent losing streak and redeem himself, he'll need to face off against his former best friend, and Tashi's ex-boyfriend.",
        poster: "https://image.tmdb.org/t/p/original/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
        runtime: "2h 11m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt16426418",
        streamingOptions : "https://media.movieofthenight.com/services/apple/logo-dark-theme.svg",
        backdrop : "#7c6254"
    },
    {
        title: "Damsel",
        imdbrating: "6.1/10",
        rottenrating: "56%",
        stars: "Millie Bobby Brown, Ray Winstone, Angela Bassett",
        directors: "Juan Carlos Fresnadillo",
        plot: "A dutiful damsel agrees to marry a handsome prince, only to find the royal family has recruited her as a sacrifice to repay an ancient debt.",
        poster: "https://image.tmdb.org/t/p/original/AgHbB9DCE9aE57zkHjSmseszh6e.jpg",
        runtime: "1h 50m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt13452446",
        streamingOptions : "https://media.movieofthenight.com/services/netflix/logo-dark-theme.svg",
        backdrop : "#3c2e1d"
    },
    {
        title: "Kingdom of the Planet of the Apes",
        imdbrating: "6.9/10",
        rottenrating: "80%",
        stars: "Owen Teague, Freya Allan, Kevin Durand",
        directors: "Wes Ball",
        plot: "Many years after the reign of Caesar, a young ape goes on a journey that will lead him to question everything he's been taught about the past and make choices that will define a future for apes and humans alike.",
        poster: "https://image.tmdb.org/t/p/original/zhyLLcwtvfNiFXDSZ2c5vOxLq2p.jpg",
        runtime: "2h 25m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt11389872",
        streamingOptions : "https://media.movieofthenight.com/services/disney/logo-dark-theme.svg",
        backdrop : "#5c5b50"
    },
    {
        title: "Madame Web",
        imdbrating: "4/10",
        rottenrating: "11%",
        stars: "Dakota Johnson, Sydney Sweeney, Isabela Merced",
        directors: "S.J. Clarkson",
        plot: "Cassandra Webb is a New York metropolis paramedic who begins to demonstrate signs of clairvoyance. Forced to challenge revelations about her past, she needs to safeguard three young women from a deadly adversary who wants them destroyed.",
        poster: "https://image.tmdb.org/t/p/original/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
        runtime: "1h 56m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt11057302",
        streamingOptions : "https://media.movieofthenight.com/services/netflix/logo-dark-theme.svg",
        backdrop: "#48282a"
    },
    {
        title: "Argylle",
        imdbrating: "5.7/10",
        rottenrating: "33%",
        stars: "Henry Cavill, Bryce Dallas Howard, Sam Rockwell",
        directors: "Matthew Vaughn",
        plot: "A reclusive author who writes espionage novels about a secret agent and a global spy syndicate realizes the plot of the new book she's writing starts to mirror real-world events, in real time.",
        poster: "https://image.tmdb.org/t/p/original/iq1t8MxKDkKuV1WqyOr2RQM0hIA.jpg",
        runtime: "2h 19m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt15009428",
        streamingOptions : "https://media.movieofthenight.com/services/netflix/logo-dark-theme.svg",
        backdrop: "#474a63"
    },
    {
        title: "Furiosa: A Mad Max Saga",
        imdbrating: "7.6/10",
        rottenrating: "90%",
        stars: "Anya Taylor-Joy, Chris Hemsworth, Tom Burke",
        directors: "George Miller",
        plot: "The origin story of renegade warrior Furiosa before her encounter and teamup with Mad Max.",
        poster: "https://image.tmdb.org/t/p/original/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
        runtime: "2h 28m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt12037194",
        streamingOptions : "https://media.movieofthenight.com/services/hbo/logo-dark-theme.svg",
        backdrop:"#7b5d3e"
    },
    {
        title: "Rebel Moon - Part Two: The Scargiver",
        imdbrating: "5.3/10",
        rottenrating: "17%",
        stars: "Sofia Boutella, Djimon Hounsou, Ed Skrein",
        directors: "Zack Snyder",
        plot: "Kora and surviving warriors prepare to defend Veldt, their new home, alongside its people against the Realm. The warriors face their pasts, revealing their motivations before the Realm's forces arrive to crush the growing rebellion.",
        poster: "https://image.tmdb.org/t/p/original/95gnJZIk2rEkMO0Ch46x5CVjnms.jpg",
        runtime: "2h 2m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt23137904",
        streamingOptions : "https://media.movieofthenight.com/services/netflix/logo-dark-theme.svg",
        backdrop : "#897263"
    },
    {
        title: "Dune: Part Two",
        imdbrating: "8.5/10",
        rottenrating: "92%",
        stars: "Timothée Chalamet, Zendaya, Rebecca Ferguson",
        directors: "Denis Villeneuve",
        plot: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
        poster: "https://image.tmdb.org/t/p/original/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
        runtime: "2h 46m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt15239678",
        streamingOptions : "https://media.movieofthenight.com/services/hbo/logo-dark-theme.svg",
        backdrop:"#983a0d"
    },
    {
        title: "The Fall Guy",
        imdbrating: "6.9/10",
        rottenrating: "82%",
        stars: "Ryan Gosling, Emily Blunt, Aaron Taylor-Johnson",
        directors: "David Leitch",
        plot: "A stuntman, fresh off an almost career-ending accident, has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job. What could possibly go right?",
        poster: "https://image.tmdb.org/t/p/original/tSz1qsmSJon0rqjHBxXZmrotuse.jpg",
        runtime: "2h 5m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt1684562",
        streamingOptions : "https://media.movieofthenight.com/services/apple/logo-dark-theme.svg",
        backdrop:"#9b9978"
    },
    {
        title: "Civil War",
        imdbrating: "7.1/10",
        rottenrating: "81%",
        stars: "Kirsten Dunst, Wagner Moura, Cailee Spaeny",
        directors: "Alex Garland",
        plot: "A journey across a dystopian future America, following a team of military-embedded journalists as they race against time to reach DC before rebel factions descend upon the White House.",
        poster: "https://image.tmdb.org/t/p/original/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
        runtime: "1h 49m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt17279496",
        streamingOptions : "https://media.movieofthenight.com/services/prime/logo-dark-theme.svg",
        backdrop:"#6b6751"
    },
    {
        title: "Twisters",
        imdbrating: "6.7/10",
        rottenrating: "75%",
        stars: "Daisy Edgar-Jones, Glen Powell, Anthony Ramos",
        directors: "Lee Isaac Chung",
        plot: "Kate Carter, a retired tornado-chaser and meteorologist, is persuaded to return to Oklahoma to work with a new team and new technologies.",
        poster: "https://image.tmdb.org/t/p/original/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
        runtime: "2h 2m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt12584954",
        streamingOptions : "https://media.movieofthenight.com/services/prime/logo-dark-theme.svg",
        backdrop:"#585955"
    },
    {
        title: "Godzilla x Kong: The New Empire",
        imdbrating: "6.1/10",
        rottenrating: "54%",
        stars: "Rebecca Hall, Brian Tyree Henry, Dan Stevens",
        directors: "Adam Wingard",
        plot: "Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins and connection to Skull Island's mysteries.",
        poster: "https://image.tmdb.org/t/p/original/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
        runtime: "1h 56m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt5034838",
        streamingOptions : "https://media.movieofthenight.com/services/hbo/logo-dark-theme.svg",
        backdrop:"#906c63"
    },
    {
        title: "Road House",
        imdbrating: "6.2/10",
        rottenrating: "59%",
        stars: "Jake Gyllenhaal, Daniela Melchior, Conor McGregor",
        directors: "Doug Liman",
        plot: "Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.",
        poster: "https://image.tmdb.org/t/p/original/cvn38vKMgFJJNzs7xwHIblUs528.jpg",
        runtime: "2h 1m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt3359350",
        streamingOptions : "https://media.movieofthenight.com/services/prime/logo-dark-theme.svg",
        backdrop:"#2c2d2a"
    },
    {
        title: "Kung Fu Panda 4",
        imdbrating: "6.3/10",
        rottenrating: "71%",
        stars: "Jack Black, Awkwafina, Viola Davis",
        directors: "Mike Mitchell, Stephanie Stine",
        plot: "After Po is tapped to become the Spiritual Leader of the Valley of Peace, he needs to find and train a new Dragon Warrior, which may be easier said than done.",
        poster: "https://image.tmdb.org/t/p/original/t1SULuKu2HMukgJdtL9HfBHumwa.jpg",
        runtime: "1h 34m",
        showType : "movie",
        releaseYear: "2024",
        imdbId : "tt21692408",
        streamingOptions : "https://media.movieofthenight.com/services/peacock/logo-dark-theme.svg",
        backdrop:"#9da474"
    },
    {
        title: "Invincible",
        imdbrating: "8.7/10",
        rottenrating: "99%",
        stars: "Steven Yeun, Sandra Oh, J.K. Simmons",
        directors: "Simon Racioppa, Jeff Allen",
        plot: "Mark Grayson is a seemingly normal teenager who gains superpowers like his father, but discovers that his father may not be the hero he seems to be.",
        poster: "https://image.tmdb.org/t/p/original/dMOpdkrDC5dQxqNydgKxXjBKyAc.jpg",
        runtime: "2 Seasons",
        episodeCount: "16",
        showType : "series",
        releaseYear: "2021-2024",
        imdbId : "tt6741278",
        streamingOptions : "https://media.movieofthenight.com/services/prime/logo-dark-theme.svg",
        backdrop:"#654128"
    },
    {
        title: "The Boys",
        imdbrating: "8.7/10",
        rottenrating: "93%",
        stars: "Karl Urban, Jack Quaid, Antony Starr",
        directors: "Eric Kripke",
        plot: "A group of vigilantes known as The Boys set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
        poster: "https://image.tmdb.org/t/p/original/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg",
        runtime: "4 Seasons",
        episodeCount: "24",
        showType : "series",
        releaseYear: "2019-2024",
        imdbId : "tt1190634",
        streamingOptions : "https://media.movieofthenight.com/services/prime/logo-dark-theme.svg",
        backdrop:"#6d484a"
    },
    {
        title: "Fallout",
        imdbrating: "8.4/10",
        rottenrating: "90%",
        stars: "Ella Purnell, Walton Goggins, Kyle MacLachlan",
        directors: "Jonathan Nolan, Lisa Joy",
        plot: "In a post-apocalyptic future, a group of survivors navigates the treacherous world of mutated creatures, hostile factions, and radiation zones while uncovering the secrets of a lost civilization.",
        poster: "https://image.tmdb.org/t/p/original/AnsSKR9LuK0T9bAOcPVA3PUvyWj.jpg",
        runtime: "1 season",
        showType : "series",
        releaseYear: "2024",        
        imdbId : "tt12637874",
        streamingOptions : "https://media.movieofthenight.com/services/prime/logo-dark-theme.svg",
        backdrop:"#716751"

    },
    {
        title: "House of the Dragon",
        imdbrating: "8.4/10",
        rottenrating: "87%",
        stars: "Paddy Considine, Matt Smith, Emma D'Arcy",
        directors: "Miguel Sapochnik, Greg Yaitanes",
        plot: "The Targaryen dynasty faces internal conflict and external threats as it navigates its way through a civil war known as the Dance of the Dragons.",
        poster: "https://image.tmdb.org/t/p/original/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
        runtime: "2 Seasons",
        episodeCount: "18",
        showType : "series",
        releaseYear: "2022-2024",
        imdbId : "tt11198330",
        streamingOptions : "https://media.movieofthenight.com/services/hbo/logo-dark-theme.svg",
        backdrop:"#2f1b11"
    },
    {
        title: "Arcane",
        imdbrating: "9.0/10",
        rottenrating: "100%",
        stars: "Hailee Steinfeld, Kevin Alejandro, Jason Spisak",
        directors: "Pascal Charrue, Arnaud Delord",
        plot: "Set in the universe of League of Legends, this series explores the origin stories of iconic champions and the conflict between the wealthy city of Piltover and the oppressed underground of Zaun.",
        poster: "https://image.tmdb.org/t/p/original/6FMWx79iAtZx8WHtOrRj0VlM8Tp.jpg",
        runtime: "2 Seasons",
        episodeCount: "9",
        showType : "series",
        releaseYear: "2021-2024",
        imdbId : "tt11126994",
        streamingOptions : "https://media.movieofthenight.com/services/netflix/logo-dark-theme.svg",
        backdrop:"#2d2b3c"
    },
    {
        title: "Shōgun",
        imdbrating: "8.7/10",
        rottenrating: "99%",
        stars: "Cosmo Jarvis, Hiroyuki Sanada, Tadanobu Asano",
        directors: "Tim Van Patten, Alex Graves",
        plot: "In the 1600s, an English navigator finds himself shipwrecked in Japan and caught between the warring factions of feudal lords.",
        poster: "https://image.tmdb.org/t/p/original/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
        runtime: "1 Season",
        episodeCount: "10",
        showType : "series",
        releaseYear: "2024",
        imdbId : "tt2788316",
        streamingOptions : "https://media.movieofthenight.com/services/netflix/logo-dark-theme.svg",
        backdrop:"#3f3937"
    }
];


export default newMovies